project:
  type: website
  output-dir: docs

website:
  title: "María Santibáñez"
  page-footer:
    center: "© 2026 María Pía Santibáñez"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
